[package]
name = "doc-host"
version = "0.1.0"
authors = ["Michael Chesser"]

[dependencies]
dotenv = "0.11"
mdbook = "0.1"
fs_extra = "1"
git2 = "0.7"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1"
serde_derive = "1"
serde_json = "1"
